config/routes.rb
# == Route Map
#
#           Prefix Verb   URI Pattern                     Controller#Action
#             root GET    /                               pages#home
# jobs_unallocated GET    /jobs/unallocated(.:format)     jobs#unallocated
#    pages_problem GET    /pages/problem(.:format)        pages#problem
#             jobs GET    /jobs(.:format)                 jobs#index
#                  POST   /jobs(.:format)                 jobs#create
#          new_job GET    /jobs/new(.:format)             jobs#new
#         edit_job GET    /jobs/:id/edit(.:format)        jobs#edit
#              job GET    /jobs/:id(.:format)             jobs#show
#                  PATCH  /jobs/:id(.:format)             jobs#update
#                  PUT    /jobs/:id(.:format)             jobs#update
#                  DELETE /jobs/:id(.:format)             jobs#destroy
#      technicians GET    /technicians(.:format)          technicians#index
#                  POST   /technicians(.:format)          technicians#create
#   new_technician GET    /technicians/new(.:format)      technicians#new
#  edit_technician GET    /technicians/:id/edit(.:format) technicians#edit
#       technician GET    /technicians/:id(.:format)      technicians#show
#                  PATCH  /technicians/:id(.:format)      technicians#update
#                  PUT    /technicians/:id(.:format)      technicians#update
#        companies GET    /companies(.:format)            companies#index
#                  POST   /companies(.:format)            companies#create
#      new_company GET    /companies/new(.:format)        companies#new
#     edit_company GET    /companies/:id/edit(.:format)   companies#edit
#          company GET    /companies/:id(.:format)        companies#show
#                  PATCH  /companies/:id(.:format)        companies#update
#                  PUT    /companies/:id(.:format)        companies#update
#                  DELETE /companies/:id(.:format)        companies#destroy
#            login GET    /login(.:format)                session#new
#                  POST   /login(.:format)                session#create
#                  DELETE /login(.:format)                session#destroy
# 

Rails.application.routes.draw do


  # get 'companies/index'
  #
  # get 'companies/new'
  #
  # get 'companies/edit'
  #
  # get 'companies/show'

  root :to => "pages#home"

  get '/jobs/unallocated' => 'jobs#unallocated'
  get '/pages/problem' => 'pages#problem'

  resources :jobs
  resources :technicians, :only => [:index, :new, :create, :edit, :update, :show]
  resources :companies


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # This session stuff is different. Start with booker and see how we go...
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id             :integer          not null, primary key
#  summary        :text
#  detail         :text
#  address        :text
#  requested_date :date
#  accepted_date  :date
#  finished       :boolean
#  booker_id      :integer
#  technician_id  :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  date_completed :date
#  photo          :text
#

class Job < ApplicationRecord
  belongs_to :booker
  belongs_to :technician, :optional => true

  validates :requested_date, :presence => true

  include PgSearch
  pg_search_scope :search_full_text, against: {
  summary: 'A',
  detail: 'B',
  address: 'C'
  }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController



  def index
    # if params[:term].length != 0
    if params[:term]
      if params[:term].length != 0
        @jobs = @current_user.company.job.search_full_text(params[:term])
      else
        @jobs = @current_user.company.job.all
      end
    else
      @jobs = @current_user.company.jobs.all
    end

  end


  def unallocated
    @jobs = @current_user.company.jobs.where('technician_id'=>nil)
  end

  def new
    @job = Job.new
  end

  def create
    job = Job.create job_params
    if job.save
      redirect_to job
    else
      redirect_to pages_problem_path
    end
  end


  def edit
    @job = Job.find params[:id]
  end

  def update
    job = Job.find params[:id]
    # raise
    if params["job"]["photo"].nil?
    else
      cloudinary = Cloudinary::Uploader.upload( params[ "job" ][ "photo" ] )
      job.photo = cloudinary["url"]
    end
    job.update job_params
    redirect_to job
  end

  def show
    @job = Job.find_by :id => params[:id]
    if @job.nil?
      flash[:error] = "Please don't enter job number in the URL. That's naughty."
      redirect_to pages_problem_path
    end

  end

  def destroy
    job = Job.find params[:id]
    job.destroy
    redirect_to jobs_path
  end


  private
  def job_params
    params.require(:job).permit(:detail, :summary, :requested_date, :address, :accepted_date, :finished, :booker_id, :technician_id, :date_completed)
  end




end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :multipart => true } do |f| %>



  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, :class => 'form-control', :required => true   %>
  </div>

  <div class="form-group">
    <%= f.label :detail %>
    <%= f.text_area :detail, :class => 'form-control tall-field', :required => true   %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, :class => 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :requested_date %>
    <%= f.text_field :requested_date, :class => 'form-control', :required => true %>
  </div>


  <% if session[:user_type] == "booker" %>
    <!-- <%= "BOOKER" -%> -->
    <div class="form-group">
      <%= f.label :accepted_date %>
      <%= f.text_field :accepted_date, :class => 'form-control'   %>
    </div>


  <% elsif session[:user_type] == "technician"%>
    <!-- <%= "TECHNICIAN" -%> -->
    <div class="form-group">
      <%= f.label :accepted_date %>
      <%= f.text_field :accepted_date, :class => 'form-control', :required => true    %>
    </div>

  <% end %>





  <div class="form-group">
    <%= f.label :date_completed %>
    <%= f.text_field :date_completed, :class => 'form-control'   %>
  </div>


  <% if session[:user_type] == "booker" %>
    <!-- <%= "BOOKER" -%> -->
    <div class="form-group hidden">
      <%= f.label :booker_id %>
      <%= f.text_field :booker_id, :value => session[:user_id], :class => 'form-control'   %>
    </div>

    <div class="form-group hidden">
      <%= f.label :technician_id %>
      <%= f.select :technician_id, Technician.pluck(:name, :id), :include_blank => true, :class => "dropdown-menu" %>
    </div>

  <% elsif session[:user_type] == "technician"%>
    <!-- <%= "TECHNICIAN" -%> -->

    <div class="form-group hidden">
      <%= f.label :technician_id %>
      <%= f.text_field :technician_id, :value => session[:user_id], :class => 'form-control'  %>
    </div>



  <% end %>


  <div class="form-group">
     <%= f.label :photo %><br>
     <%= f.file_field :photo %>
   </div>



  <div class="form-group">
    <label></label>
    <%= f.submit :class => 'btn btn-info'  %>
  </div>




<% end %>





<% if session[:user_type] == "booker" %>
  <!-- <%= "BOOKER" -%> -->
  <p>Adding or editing a job will assign you as the job's booker. You are logged in as "<%= @current_user.name %>. You cannot assign a technician, the technician must accept the job themselves."</p>

<% elsif session[:user_type] == "technician"%>
  <!-- <%= "TECHNICIAN" -%> -->
  <p>Editing a job will assign you as the job's technician. You are logged in as "<%= @current_user.name %>"</p>
<% end %>

app/views/jobs/_list.html.erb
<% @today = Time.new.to_date %>


<% @jobs = @jobs.sort_by{ |t| t.requested_date  } %>


<div class="joblist">

  <% @jobs.each do |job| %>

    <% class_words = "job col-md-3 "  %>

    <% if job.accepted_date == nil %>
      <% class_words = class_words + "unallocated " %>
    <% else %>
      <% class_words = class_words + "allocated " %>
    <% end %>

    <% if job.date_completed == nil %>
      <% class_words = class_words + "open " %>
    <% else %>
      <% class_words = class_words + "closed " %>
    <% end %>

    <% if (job.requested_date < @today) %>
      <% class_words = class_words + "overdue " %>
    <% else %>
      <% class_words = class_words + "ontrack " %>
    <% end %>

    <% class_words = class_words.split(" ") %>


    <%= tag("div", class: class_words) %>
    <!-- <div class="<%= class_words %>"> -->
      <ul>
        <h4><%= link_to job.summary, job %></h4>
        <li>Address: <%= job.address %></li>
        <li>Requested Date: <%= job.requested_date %></li>
        <li>Planned Date: <%= job.accepted_date %></li>
        <li>Completed Date: <%= job.date_completed %></li>
        <li>Booker: <%= job.booker.name %></li>

        <% if job.technician_id.nil? %>
          <li>Technician: TBC</li>
        <% else %>
          <li>Technician: <%= job.technician.name %></li>
        <% end %>

      </ul>
    </div>


  <% end %>


</div>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>


<%= render :partial => "form" %>

app/views/jobs/index.html.erb
<h1>List of Jobs</h1>


<%= render :partial => "list" %>

app/views/jobs/new.html.erb
<h1>Add New Job</h1>

<% if @current_user.present? %> <!-- someone is logged in -->
  <% if session[:user_type] == "booker" %>
    <%= render :partial => "form" %>
  <% elsif session[:user_type] == "technician"%>
    <h2>Only a <i>Booker</i> can add a new job</h2>
  <% end %>
  <% else %>
  <%= link_to "Not logged in...", root_path %></li>
<% end %>

app/views/jobs/search.html.erb
<h1>Search Results</h1>
<p>Searching within Summary and Detail fields...</p>


<%= render :partial => "list" %>

app/views/jobs/show.html.erb
<div class="col-md-12">

  <div class="job closed">

    <%= button_to "Edit Job", edit_job_path(@job), :method => 'get', :class => "btn btn-primary", form: {style: 'display:inline-block;'} %>
    <%= button_to 'Delete Job', @job, :method => 'delete', :class => "btn btn-danger", :data => { :confirm => 'Are you sure?'}, form: {style: 'display:inline-block;'} %>

  </div>




  <div class="job minicon container">
    <ul>
      <h2><%= @job.summary %></h2>
    </ul>

    <div class="col-md-3" >
      <ul>


        <li>Address: <%= @job.address %></li>
        <li>Requested Date: <%= @job.requested_date %></li>
        <li>Planned Date: <%= @job.accepted_date %></li>
        <li>Completed Date: <%= @job.date_completed %></li>

        <li>Booker: <%= @job.booker.name %></li>
        <% if @job.technician_id.nil? %>
          <li>Technician: TBC</li>
        <% else %>
          <li>Technician: <%= @job.technician.name %></li>
        <% end %>
      </ul>
    </div>

    <div  class="col-md-9 ">
      <p><%= @job.detail %></p>
    </div>
  </div>



  <% if @job.photo.nil? %>
  <% else %>
  <div class=" mt-1em ">
    <%= cl_image_tag(@job.photo, :class => 'img-rounded photo') unless @job.photo.nil? %>
  </div>
  <% end %>


</div>

app/views/jobs/unallocated.html.erb
<h1>Unallocated Jobs</h1>


<div class="joblist">

  <% @jobs.each do |job| %>

    <div class="job col-md-3 closed">
      <ul>
        <h3><%= link_to job.summary, job %></h3>
        <li>Info: <%= job.detail %></li>
        <li>Address: <%= job.address %></li>
        <li>Requested Date: <%= job.requested_date %></li>
        <li>Booker: <%= job.booker.name %></li>
      </ul>
    </div>

  <% end %>
</div>